### ISSUE TITLE
ERROR [app-builder 5/6] RUN npm prune

### ISSUE THREAD

**Issue by ManuelReschke** [alankrantas/svelteapp-typescript-go#43]
I got the following error after npm run docker.

 > [app-builder 5/6] RUN npm prune:
#0 4.754 npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
#0 6.614 npm ERR! code 1
#0 6.614 npm ERR! path /app/node_modules/esbuild
#0 6.615 npm ERR! command failed
#0 6.616 npm ERR! command sh -c node install.js
#0 6.616 npm ERR! node:internal/errors:496
#0 6.616 npm ERR!     ErrorCaptureStackTrace(err);
#0 6.616 npm ERR!     ^
#0 6.616 npm ERR! 
#0 6.616 npm ERR! <ref *1> Error: spawnSync /app/node_modules/esbuild/bin/esbuild ETXTBSY
#0 6.616 npm ERR!     at Object.spawnSync (node:internal/child_process:1117:20)
#0 6.616 npm ERR!     at spawnSync (node:child_process:871:24)
#0 6.616 npm ERR!     at Object.execFileSync (node:child_process:914:15)
#0 6.616 npm ERR!     at validateBinaryVersion (/app/node_modules/esbuild/install.js:98:28)
#0 6.616 npm ERR!     at /app/node_modules/esbuild/install.js:285:5 {
#0 6.616 npm ERR!   errno: -26,
#0 6.616 npm ERR!   code: 'ETXTBSY',
#0 6.616 npm ERR!   syscall: 'spawnSync /app/node_modules/esbuild/bin/esbuild',
#0 6.616 npm ERR!   path: '/app/node_modules/esbuild/bin/esbuild',
#0 6.616 npm ERR!   spawnargs: [ '--version' ],
#0 6.616 npm ERR!   error: [Circular *1],
#0 6.616 npm ERR!   status: null,
#0 6.616 npm ERR!   signal: null,
#0 6.616 npm ERR!   output: null,
#0 6.616 npm ERR!   pid: 0,
#0 6.616 npm ERR!   stdout: null,
#0 6.616 npm ERR!   stderr: null
#0 6.616 npm ERR! }
#0 6.616 npm ERR! 
#0 6.616 npm ERR! Node.js v20.3.1
#0 6.617 
#0 6.618 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-07-05T20_57_15_688Z-debug-0.log

**Comment by alankrantas** [comment]
Due to some strange reason ```npm install --package-lock-only``` does not setup ```./svelte-kit``` properly in the container and cause failures in ```npm prune``` or ```npm run build```.

```npm i``` seems to work for now.
